cursgit/filmoteca

- llibres/la_casa_de_los_espiritus.md
Añado el libro La casa de los espiritus
> La casa de los espiritus

- series/the-office.md
Añadida la serie The Office para la actividad del bloque 5
> Añadida la serie The Office

- llibres/a-sangre-fria.md
Afegit un dels llibres més venuts del true crime que narra el brutal assassinat dels quatre membres d'una família de Kansas.
> Afegit llibre A sangre fría

- series/stranger-things.md
Aquesta contribució afegeix informació sobre la sèrie Stranger Things, incloent sinopsi, gèneres i les seues temporades.
> Afegida la sèrie 'Stranger Things'

- llibres/fundacio.md
S'ha afegit el llibre 'Fundació', d'Isaac Asimov.
> Llibre: Fundació

- pelicules/piratas-silicon-valley
Añado pelicula Piratas de Silicon Valley
> Pelicula: Piratas de Silicon Valley

- llibres/un-mon-feliç.md
Afegit el llibre "Un món feliç"
> Llibre: Un món feliç

- series/silicon-valley.md
Afegida la sèrie 'Silicon Valley'
> Sèrie: Silicon Valley

- series/blacklist.md
He afegit la sèrie The Blacklist sobre la lluita criminal de la FBI
> Sèries: Blacklist

- series/chernobyl.md
Añadida la serie Chernobyl para la actividad 5 del bloque 6: Gestión de proyectos.
> Sèrie: Chernobyl

- series/the-last-of-us.md
Añadido el archivo the-last-of-us.md al directorio series con información de la serie de HBO.
> Sèrie: The Last of Us añadida

- pelicules/El-niño-que-domó-el-viento.md
Añadida la película El niño que domó el viento para la tarea 5: Colaboración mediante Pull Requests
> Pel·lícula: El niño que domó el viento

- llibres/el-asesinato-de-roger-ackroyd.md
Se agrega un nuevo libro al repositorio: El asesinato de Roger Ackroyd de Agatha Christie
> Llibre: El asesinato de Roger Ackroyd

- pelicules/pulp-fiction.md
Se ha añadido una nueva película: Pulp Fiction
> Pel·lícula: Pulp Fiction

- llibres/el-nombre-de-la-rosa.md
S'ha afegit el llibre el nombre de la rosa al fitxer llibres.
> Llibre: el nombre de la rosa

- series/the-big-bang-theory.md
Serie nueva. 
The Big Bang Theory
> serie the big bang theory

- series/dark.md
He añadido información sobre la serie dark dentro del directorio series
> Sèrie: Dark

- llibres/dune.md
Propuesta de añadir el libro Dune
> Afegit el llibre: Dune

- series/knight-rider.md
Afegida la sèrie Knight Rider al directori corresponent.
> Sèrie: Knight Rider

- pelicules/camino-a-la-perdicion.md
Se ha añadido la pelicula camino a la perdición a peliculas
> Pel·lícula: Camino a la perdición

- pelicules/Stardust.md
He añadido el fichero  Stardust.md  al directorio pelicules. Dicho fichero contiene el título, una sinopsis y el reparto principal de la película.
> Pel·lícula: Stardust
